//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_IncentiveMechanismSimulatorMVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bids
    {
        public int Id { get; set; }
        public int Pid { get; set; }
        public int Fid { get; set; }
        public double AmountBid { get; set; }
        public int ResourceQty { get; set; }
        public double DataQty { get; set; }
        public double DataQuality { get; set; }
        public bool Success { get; set; }
        public int Gid { get; set; }
    
        public virtual Federations Federations { get; set; }
        public virtual Participants Participants { get; set; }
    }
}
