//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_IncentiveMechanismSimulatorMVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FederationHistory
    {
        public int Id { get; set; }
        public int Fid { get; set; }
        public double Progression { get; set; }
        public double Turn { get; set; }
        public double Asset { get; set; }
        public double TimeLeftInState { get; set; }
        public string State { get; set; }
        public double MarketShare { get; set; }
        public double ModelQuality { get; set; }
        public int Gid { get; set; }
    
        public virtual Federations Federations { get; set; }
    }
}
