//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_IncentiveMechanismSimulatorMVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInstance
    {
        public GameInstance()
        {
            this.Federations = new HashSet<Federations>();
            this.Participants = new HashSet<Participants>();
        }
    
        public int Id { get; set; }
        public string Gid { get; set; }
        public double MarketShare { get; set; }
        public double StartingAsset { get; set; }
        public double MinTrainingLength { get; set; }
        public double MaxTrainingLength { get; set; }
        public double MinBidLength { get; set; }
        public double MinProfitLength { get; set; }
        public int NumFederations { get; set; }
        public int NumPlayers { get; set; }
        public double MinDataQuality { get; set; }
        public double MaxDataQUality { get; set; }
        public double MinDataQuantity { get; set; }
        public double MaxDataQuantity { get; set; }
        public double DataQualityWeight { get; set; }
        public double DataQuantityWeight { get; set; }
        public int MinResourceQuantity { get; set; }
        public int MaxResourceQuantity { get; set; }
        public double InitDataQualityTh { get; set; }
        public double InitDataQuantityTh { get; set; }
        public int InitResourceQuantityTh { get; set; }
        public int InitAmountTh { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int MaxTurns { get; set; }
        public double MarketShareFederationPct { get; set; }
    
        public virtual ICollection<Federations> Federations { get; set; }
        public virtual ICollection<Participants> Participants { get; set; }
    }
}
